### ISSUE TITLE
Streak Days unwanted spacing

### ISSUE THREAD

**Issue by Daneel87** [chaudharydeepanshu/clean_calendar#3]
As you can see from the screenshot, there are unwanted spaces in streak days.

![issue](https://user-images.githubusercontent.com/586309/192332013-19e68b4b-ac28-4ab3-be48-6a2b68accc40.png)

**Comment by chaudharydeepanshu** [comment]
Thanks for reporting I'm looking into it.

**Comment by chaudharydeepanshu** [comment]
@Daneel87 Thank you for reporting and keeping patience.
I have been able to recreate this bug. It was due to the use of hardcoded start and end weekdays in streak date widgets which were not updated according to the new addition of property startWeekday in the recent update.

But now I have updated the plugin to fix this issue.

Also, let me know if you face any further issues.
Thank you.
